@baseUrl = http://localhost:3000

### Checkout - sucesso
POST {{baseUrl}}/api/checkout
Content-Type: application/json

{
  "userName": "Guilherme",
  "email": "gui@fullcycle.com.br",
  "password": "senhaforte",
  "courseId": 2,
  "cardNumber": "4111222233334444"
}

### Checkout - pagamento recusado
POST {{baseUrl}}/api/checkout
Content-Type: application/json

{
  "userName": "João",
  "email": "joao@teste.com",
  "password": "123",
  "courseId": 1,
  "cardNumber": "5111222233334444"
}

### Relatório financeiro administrativo
GET {{baseUrl}}/api/admin/financial-report
x-admin-key: dev-only-insecure-admin-key

### Deletar usuário
DELETE {{baseUrl}}/api/users/1
x-admin-key: dev-only-insecure-admin-key
