STATUS_PENDENTE = 'pendente'
STATUS_APROVADO = 'aprovado'
STATUS_ENVIADO = 'enviado'
STATUS_ENTREGUE = 'entregue'
STATUS_CANCELADO = 'cancelado'
STATUS_VALIDOS = [STATUS_PENDENTE, STATUS_APROVADO, STATUS_ENVIADO, STATUS_ENTREGUE, STATUS_CANCELADO]

CATEGORIAS_VALIDAS = ['informatica', 'moveis', 'vestuario', 'geral', 'eletronicos', 'livros']

NOME_MIN_LEN = 2
NOME_MAX_LEN = 200

LIMITE_DESCONTO_ALTO = 10000
LIMITE_DESCONTO_MEDIO = 5000
LIMITE_DESCONTO_BAIXO = 1000

DESCONTO_ALTO = 0.10
DESCONTO_MEDIO = 0.05
DESCONTO_BAIXO = 0.02

TIPO_ADMIN = 'admin'
TIPO_CLIENTE = 'cliente'
